/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.vizual.viz.ContainerTag;
import org.xtext.example.vizual.viz.NormalTag;
import org.xtext.example.vizual.viz.VizPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Container Tag</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.impl.ContainerTagImpl#getNormalTags <em>Normal Tags</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ContainerTagImpl extends NormalTagImpl implements ContainerTag
{
  /**
   * The cached value of the '{@link #getNormalTags() <em>Normal Tags</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNormalTags()
   * @generated
   * @ordered
   */
  protected EList<NormalTag> normalTags;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ContainerTagImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VizPackage.Literals.CONTAINER_TAG;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<NormalTag> getNormalTags()
  {
    if (normalTags == null)
    {
      normalTags = new EObjectContainmentEList<NormalTag>(NormalTag.class, this, VizPackage.CONTAINER_TAG__NORMAL_TAGS);
    }
    return normalTags;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case VizPackage.CONTAINER_TAG__NORMAL_TAGS:
        return ((InternalEList<?>)getNormalTags()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VizPackage.CONTAINER_TAG__NORMAL_TAGS:
        return getNormalTags();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VizPackage.CONTAINER_TAG__NORMAL_TAGS:
        getNormalTags().clear();
        getNormalTags().addAll((Collection<? extends NormalTag>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VizPackage.CONTAINER_TAG__NORMAL_TAGS:
        getNormalTags().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VizPackage.CONTAINER_TAG__NORMAL_TAGS:
        return normalTags != null && !normalTags.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ContainerTagImpl
