/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractVizScopeProvider extends DelegatingScopeProvider {
}
