/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Create</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.Create#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xtext.example.vizual.viz.Create#getBullets <em>Bullets</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vizual.viz.VizPackage#getCreate()
 * @model
 * @generated
 */
public interface Create extends CommonCommand
{
  /**
   * Returns the value of the '<em><b>Command</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.vizual.viz.CreateBulletPoints}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Command</em>' attribute.
   * @see org.xtext.example.vizual.viz.CreateBulletPoints
   * @see #setCommand(CreateBulletPoints)
   * @see org.xtext.example.vizual.viz.VizPackage#getCreate_Command()
   * @model
   * @generated
   */
  CreateBulletPoints getCommand();

  /**
   * Sets the value of the '{@link org.xtext.example.vizual.viz.Create#getCommand <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Command</em>' attribute.
   * @see org.xtext.example.vizual.viz.CreateBulletPoints
   * @see #getCommand()
   * @generated
   */
  void setCommand(CreateBulletPoints value);

  /**
   * Returns the value of the '<em><b>Bullets</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bullets</em>' attribute.
   * @see #setBullets(String)
   * @see org.xtext.example.vizual.viz.VizPackage#getCreate_Bullets()
   * @model
   * @generated
   */
  String getBullets();

  /**
   * Sets the value of the '{@link org.xtext.example.vizual.viz.Create#getBullets <em>Bullets</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bullets</em>' attribute.
   * @see #getBullets()
   * @generated
   */
  void setBullets(String value);

} // Create
