/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Div</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.Div#getDivision <em>Division</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vizual.viz.VizPackage#getDiv()
 * @model
 * @generated
 */
public interface Div extends EObject
{
  /**
   * Returns the value of the '<em><b>Division</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Division</em>' attribute.
   * @see #setDivision(String)
   * @see org.xtext.example.vizual.viz.VizPackage#getDiv_Division()
   * @model
   * @generated
   */
  String getDivision();

  /**
   * Sets the value of the '{@link org.xtext.example.vizual.viz.Div#getDivision <em>Division</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Division</em>' attribute.
   * @see #getDivision()
   * @generated
   */
  void setDivision(String value);

} // Div
