/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Header</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.TableHeader#getText <em>Text</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vizual.viz.VizPackage#getTableHeader()
 * @model
 * @generated
 */
public interface TableHeader extends CommonCommand
{
  /**
   * Returns the value of the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Text</em>' attribute.
   * @see #setText(String)
   * @see org.xtext.example.vizual.viz.VizPackage#getTableHeader_Text()
   * @model
   * @generated
   */
  String getText();

  /**
   * Sets the value of the '{@link org.xtext.example.vizual.viz.TableHeader#getText <em>Text</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Text</em>' attribute.
   * @see #getText()
   * @generated
   */
  void setText(String value);

} // TableHeader
