/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Row</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.TableRow#getData <em>Data</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vizual.viz.VizPackage#getTableRow()
 * @model
 * @generated
 */
public interface TableRow extends CommonCommand
{
  /**
   * Returns the value of the '<em><b>Data</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.vizual.viz.CommonCommand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data</em>' containment reference list.
   * @see org.xtext.example.vizual.viz.VizPackage#getTableRow_Data()
   * @model containment="true"
   * @generated
   */
  EList<CommonCommand> getData();

} // TableRow
