/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Data</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.TableData#getDataValue <em>Data Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vizual.viz.VizPackage#getTableData()
 * @model
 * @generated
 */
public interface TableData extends CommonCommand
{
  /**
   * Returns the value of the '<em><b>Data Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Data Value</em>' attribute.
   * @see #setDataValue(String)
   * @see org.xtext.example.vizual.viz.VizPackage#getTableData_DataValue()
   * @model
   * @generated
   */
  String getDataValue();

  /**
   * Sets the value of the '{@link org.xtext.example.vizual.viz.TableData#getDataValue <em>Data Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Data Value</em>' attribute.
   * @see #getDataValue()
   * @generated
   */
  void setDataValue(String value);

} // TableData
