/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.vizual.viz.VizPackage
 * @generated
 */
public interface VizFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VizFactory eINSTANCE = org.xtext.example.vizual.viz.impl.VizFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Command</em>'.
   * @generated
   */
  Command createCommand();

  /**
   * Returns a new object of class '<em>Head Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Head Command</em>'.
   * @generated
   */
  HeadCommand createHeadCommand();

  /**
   * Returns a new object of class '<em>Body Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Body Command</em>'.
   * @generated
   */
  BodyCommand createBodyCommand();

  /**
   * Returns a new object of class '<em>Title Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Title Command</em>'.
   * @generated
   */
  TitleCommand createTitleCommand();

  /**
   * Returns a new object of class '<em>Common Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Common Command</em>'.
   * @generated
   */
  CommonCommand createCommonCommand();

  /**
   * Returns a new object of class '<em>Div Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Div Command</em>'.
   * @generated
   */
  DivCommand createDivCommand();

  /**
   * Returns a new object of class '<em>Create</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Create</em>'.
   * @generated
   */
  Create createCreate();

  /**
   * Returns a new object of class '<em>Text Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Text Command</em>'.
   * @generated
   */
  TextCommand createTextCommand();

  /**
   * Returns a new object of class '<em>Div</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Div</em>'.
   * @generated
   */
  Div createDiv();

  /**
   * Returns a new object of class '<em>Table Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Command</em>'.
   * @generated
   */
  TableCommand createTableCommand();

  /**
   * Returns a new object of class '<em>Table Row</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Row</em>'.
   * @generated
   */
  TableRow createTableRow();

  /**
   * Returns a new object of class '<em>Table Header</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Header</em>'.
   * @generated
   */
  TableHeader createTableHeader();

  /**
   * Returns a new object of class '<em>Table Data</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Table Data</em>'.
   * @generated
   */
  TableData createTableData();

  /**
   * Returns a new object of class '<em>Initializer</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Initializer</em>'.
   * @generated
   */
  Initializer createInitializer();

  /**
   * Returns a new object of class '<em>Drop Down Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drop Down Command</em>'.
   * @generated
   */
  DropDownCommand createDropDownCommand();

  /**
   * Returns a new object of class '<em>Bullet Point Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Bullet Point Command</em>'.
   * @generated
   */
  BulletPointCommand createBulletPointCommand();

  /**
   * Returns a new object of class '<em>Numbered List Command</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Numbered List Command</em>'.
   * @generated
   */
  NumberedListCommand createNumberedListCommand();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  VizPackage getVizPackage();

} //VizFactory
