/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.vizual.viz.VizFactory
 * @model kind="package"
 * @generated
 */
public interface VizPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "viz";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/vizual/Viz";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "viz";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VizPackage eINSTANCE = org.xtext.example.vizual.viz.impl.VizPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.ModelImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__COMMANDS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.CommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__HTML = 0;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__END_HTML = 1;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.HeadCommandImpl <em>Head Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.HeadCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getHeadCommand()
   * @generated
   */
  int HEAD_COMMAND = 2;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEAD_COMMAND__HTML = COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEAD_COMMAND__END_HTML = COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Title</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEAD_COMMAND__TITLE = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Head Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEAD_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.BodyCommandImpl <em>Body Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.BodyCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getBodyCommand()
   * @generated
   */
  int BODY_COMMAND = 3;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_COMMAND__HTML = COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_COMMAND__END_HTML = COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_COMMAND__CHILDREN = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Body Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BODY_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.TitleCommandImpl <em>Title Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.TitleCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTitleCommand()
   * @generated
   */
  int TITLE_COMMAND = 4;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_COMMAND__TEXT = 0;

  /**
   * The number of structural features of the '<em>Title Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.CommonCommandImpl <em>Common Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.CommonCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCommonCommand()
   * @generated
   */
  int COMMON_COMMAND = 5;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_COMMAND__HTML = COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_COMMAND__END_HTML = COMMAND__END_HTML;

  /**
   * The number of structural features of the '<em>Common Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMON_COMMAND_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.DivCommandImpl <em>Div Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.DivCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getDivCommand()
   * @generated
   */
  int DIV_COMMAND = 6;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_COMMAND__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_COMMAND__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Div</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_COMMAND__DIV = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Div Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_COMMAND__DIV_TEXT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Div Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_COMMAND_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.CreateImpl <em>Create</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.CreateImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCreate()
   * @generated
   */
  int CREATE = 7;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE__COMMAND = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Bullets</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE__BULLETS = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Create</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.TextCommandImpl <em>Text Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.TextCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTextCommand()
   * @generated
   */
  int TEXT_COMMAND = 8;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_COMMAND__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_COMMAND__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Heading</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_COMMAND__HEADING = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_COMMAND__TEXT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Text Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_COMMAND_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.DivImpl <em>Div</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.DivImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getDiv()
   * @generated
   */
  int DIV = 9;

  /**
   * The feature id for the '<em><b>Division</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV__DIVISION = 0;

  /**
   * The number of structural features of the '<em>Div</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIV_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.TableCommandImpl <em>Table Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.TableCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableCommand()
   * @generated
   */
  int TABLE_COMMAND = 10;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COMMAND__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COMMAND__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Rows</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COMMAND__ROWS = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_COMMAND_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.TableRowImpl <em>Table Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.TableRowImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableRow()
   * @generated
   */
  int TABLE_ROW = 11;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Data</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW__DATA = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ROW_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.TableHeaderImpl <em>Table Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.TableHeaderImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableHeader()
   * @generated
   */
  int TABLE_HEADER = 12;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_HEADER__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_HEADER__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Text</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_HEADER__TEXT = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_HEADER_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.TableDataImpl <em>Table Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.TableDataImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableData()
   * @generated
   */
  int TABLE_DATA = 13;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_DATA__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_DATA__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Data Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_DATA__DATA_VALUE = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_DATA_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.InitializerImpl <em>Initializer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.InitializerImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getInitializer()
   * @generated
   */
  int INITIALIZER = 14;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZER__HTML = COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZER__END_HTML = COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Lang</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZER__LANG = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Initializer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INITIALIZER_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.DropDownCommandImpl <em>Drop Down Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.DropDownCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getDropDownCommand()
   * @generated
   */
  int DROP_DOWN_COMMAND = 15;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_DOWN_COMMAND__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_DOWN_COMMAND__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_DOWN_COMMAND__LABEL = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Options</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_DOWN_COMMAND__OPTIONS = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Drop Down Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_DOWN_COMMAND_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.BulletPointCommandImpl <em>Bullet Point Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.BulletPointCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getBulletPointCommand()
   * @generated
   */
  int BULLET_POINT_COMMAND = 16;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BULLET_POINT_COMMAND__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BULLET_POINT_COMMAND__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BULLET_POINT_COMMAND__CHILDREN = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bullet Point Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BULLET_POINT_COMMAND_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.NumberedListCommandImpl <em>Numbered List Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.NumberedListCommandImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getNumberedListCommand()
   * @generated
   */
  int NUMBERED_LIST_COMMAND = 17;

  /**
   * The feature id for the '<em><b>Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_LIST_COMMAND__HTML = COMMON_COMMAND__HTML;

  /**
   * The feature id for the '<em><b>End Html</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_LIST_COMMAND__END_HTML = COMMON_COMMAND__END_HTML;

  /**
   * The feature id for the '<em><b>Children</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_LIST_COMMAND__CHILDREN = COMMON_COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Numbered List Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBERED_LIST_COMMAND_FEATURE_COUNT = COMMON_COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.HtmlCommand <em>Html Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.HtmlCommand
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getHtmlCommand()
   * @generated
   */
  int HTML_COMMAND = 18;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.EndHtmlCommand <em>End Html Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.EndHtmlCommand
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getEndHtmlCommand()
   * @generated
   */
  int END_HTML_COMMAND = 19;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.CreateBulletPoints <em>Create Bullet Points</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.CreateBulletPoints
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCreateBulletPoints()
   * @generated
   */
  int CREATE_BULLET_POINTS = 20;


  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.vizual.viz.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.Model#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see org.xtext.example.vizual.viz.Model#getCommands()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Commands();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see org.xtext.example.vizual.viz.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.Command#getHtml <em>Html</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Html</em>'.
   * @see org.xtext.example.vizual.viz.Command#getHtml()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Html();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.Command#getEndHtml <em>End Html</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End Html</em>'.
   * @see org.xtext.example.vizual.viz.Command#getEndHtml()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_EndHtml();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.HeadCommand <em>Head Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Head Command</em>'.
   * @see org.xtext.example.vizual.viz.HeadCommand
   * @generated
   */
  EClass getHeadCommand();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.vizual.viz.HeadCommand#getTitle <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Title</em>'.
   * @see org.xtext.example.vizual.viz.HeadCommand#getTitle()
   * @see #getHeadCommand()
   * @generated
   */
  EReference getHeadCommand_Title();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.BodyCommand <em>Body Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Body Command</em>'.
   * @see org.xtext.example.vizual.viz.BodyCommand
   * @generated
   */
  EClass getBodyCommand();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.BodyCommand#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see org.xtext.example.vizual.viz.BodyCommand#getChildren()
   * @see #getBodyCommand()
   * @generated
   */
  EReference getBodyCommand_Children();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.TitleCommand <em>Title Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title Command</em>'.
   * @see org.xtext.example.vizual.viz.TitleCommand
   * @generated
   */
  EClass getTitleCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.TitleCommand#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.vizual.viz.TitleCommand#getText()
   * @see #getTitleCommand()
   * @generated
   */
  EAttribute getTitleCommand_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.CommonCommand <em>Common Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Common Command</em>'.
   * @see org.xtext.example.vizual.viz.CommonCommand
   * @generated
   */
  EClass getCommonCommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.DivCommand <em>Div Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div Command</em>'.
   * @see org.xtext.example.vizual.viz.DivCommand
   * @generated
   */
  EClass getDivCommand();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.vizual.viz.DivCommand#getDiv <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Div</em>'.
   * @see org.xtext.example.vizual.viz.DivCommand#getDiv()
   * @see #getDivCommand()
   * @generated
   */
  EReference getDivCommand_Div();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.DivCommand#getDivText <em>Div Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Div Text</em>'.
   * @see org.xtext.example.vizual.viz.DivCommand#getDivText()
   * @see #getDivCommand()
   * @generated
   */
  EAttribute getDivCommand_DivText();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.Create <em>Create</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create</em>'.
   * @see org.xtext.example.vizual.viz.Create
   * @generated
   */
  EClass getCreate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.Create#getCommand <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Command</em>'.
   * @see org.xtext.example.vizual.viz.Create#getCommand()
   * @see #getCreate()
   * @generated
   */
  EAttribute getCreate_Command();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.Create#getBullets <em>Bullets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bullets</em>'.
   * @see org.xtext.example.vizual.viz.Create#getBullets()
   * @see #getCreate()
   * @generated
   */
  EAttribute getCreate_Bullets();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.TextCommand <em>Text Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Command</em>'.
   * @see org.xtext.example.vizual.viz.TextCommand
   * @generated
   */
  EClass getTextCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.TextCommand#getHeading <em>Heading</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Heading</em>'.
   * @see org.xtext.example.vizual.viz.TextCommand#getHeading()
   * @see #getTextCommand()
   * @generated
   */
  EAttribute getTextCommand_Heading();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.TextCommand#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.vizual.viz.TextCommand#getText()
   * @see #getTextCommand()
   * @generated
   */
  EAttribute getTextCommand_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.Div <em>Div</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Div</em>'.
   * @see org.xtext.example.vizual.viz.Div
   * @generated
   */
  EClass getDiv();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.Div#getDivision <em>Division</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Division</em>'.
   * @see org.xtext.example.vizual.viz.Div#getDivision()
   * @see #getDiv()
   * @generated
   */
  EAttribute getDiv_Division();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.TableCommand <em>Table Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Command</em>'.
   * @see org.xtext.example.vizual.viz.TableCommand
   * @generated
   */
  EClass getTableCommand();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.TableCommand#getRows <em>Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rows</em>'.
   * @see org.xtext.example.vizual.viz.TableCommand#getRows()
   * @see #getTableCommand()
   * @generated
   */
  EReference getTableCommand_Rows();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.TableRow <em>Table Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Row</em>'.
   * @see org.xtext.example.vizual.viz.TableRow
   * @generated
   */
  EClass getTableRow();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.TableRow#getData <em>Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Data</em>'.
   * @see org.xtext.example.vizual.viz.TableRow#getData()
   * @see #getTableRow()
   * @generated
   */
  EReference getTableRow_Data();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.TableHeader <em>Table Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Header</em>'.
   * @see org.xtext.example.vizual.viz.TableHeader
   * @generated
   */
  EClass getTableHeader();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.TableHeader#getText <em>Text</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Text</em>'.
   * @see org.xtext.example.vizual.viz.TableHeader#getText()
   * @see #getTableHeader()
   * @generated
   */
  EAttribute getTableHeader_Text();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.TableData <em>Table Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Data</em>'.
   * @see org.xtext.example.vizual.viz.TableData
   * @generated
   */
  EClass getTableData();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.TableData#getDataValue <em>Data Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Data Value</em>'.
   * @see org.xtext.example.vizual.viz.TableData#getDataValue()
   * @see #getTableData()
   * @generated
   */
  EAttribute getTableData_DataValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.Initializer <em>Initializer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Initializer</em>'.
   * @see org.xtext.example.vizual.viz.Initializer
   * @generated
   */
  EClass getInitializer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.Initializer#getLang <em>Lang</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Lang</em>'.
   * @see org.xtext.example.vizual.viz.Initializer#getLang()
   * @see #getInitializer()
   * @generated
   */
  EAttribute getInitializer_Lang();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.DropDownCommand <em>Drop Down Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drop Down Command</em>'.
   * @see org.xtext.example.vizual.viz.DropDownCommand
   * @generated
   */
  EClass getDropDownCommand();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.DropDownCommand#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.xtext.example.vizual.viz.DropDownCommand#getLabel()
   * @see #getDropDownCommand()
   * @generated
   */
  EAttribute getDropDownCommand_Label();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.vizual.viz.DropDownCommand#getOptions <em>Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Options</em>'.
   * @see org.xtext.example.vizual.viz.DropDownCommand#getOptions()
   * @see #getDropDownCommand()
   * @generated
   */
  EAttribute getDropDownCommand_Options();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.BulletPointCommand <em>Bullet Point Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bullet Point Command</em>'.
   * @see org.xtext.example.vizual.viz.BulletPointCommand
   * @generated
   */
  EClass getBulletPointCommand();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.BulletPointCommand#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see org.xtext.example.vizual.viz.BulletPointCommand#getChildren()
   * @see #getBulletPointCommand()
   * @generated
   */
  EReference getBulletPointCommand_Children();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.NumberedListCommand <em>Numbered List Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Numbered List Command</em>'.
   * @see org.xtext.example.vizual.viz.NumberedListCommand
   * @generated
   */
  EClass getNumberedListCommand();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.NumberedListCommand#getChildren <em>Children</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Children</em>'.
   * @see org.xtext.example.vizual.viz.NumberedListCommand#getChildren()
   * @see #getNumberedListCommand()
   * @generated
   */
  EReference getNumberedListCommand_Children();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.vizual.viz.HtmlCommand <em>Html Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Html Command</em>'.
   * @see org.xtext.example.vizual.viz.HtmlCommand
   * @generated
   */
  EEnum getHtmlCommand();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.vizual.viz.EndHtmlCommand <em>End Html Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>End Html Command</em>'.
   * @see org.xtext.example.vizual.viz.EndHtmlCommand
   * @generated
   */
  EEnum getEndHtmlCommand();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.vizual.viz.CreateBulletPoints <em>Create Bullet Points</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Create Bullet Points</em>'.
   * @see org.xtext.example.vizual.viz.CreateBulletPoints
   * @generated
   */
  EEnum getCreateBulletPoints();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VizFactory getVizFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.ModelImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__COMMANDS = eINSTANCE.getModel_Commands();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.CommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Html</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__HTML = eINSTANCE.getCommand_Html();

    /**
     * The meta object literal for the '<em><b>End Html</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__END_HTML = eINSTANCE.getCommand_EndHtml();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.HeadCommandImpl <em>Head Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.HeadCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getHeadCommand()
     * @generated
     */
    EClass HEAD_COMMAND = eINSTANCE.getHeadCommand();

    /**
     * The meta object literal for the '<em><b>Title</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HEAD_COMMAND__TITLE = eINSTANCE.getHeadCommand_Title();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.BodyCommandImpl <em>Body Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.BodyCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getBodyCommand()
     * @generated
     */
    EClass BODY_COMMAND = eINSTANCE.getBodyCommand();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BODY_COMMAND__CHILDREN = eINSTANCE.getBodyCommand_Children();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.TitleCommandImpl <em>Title Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.TitleCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTitleCommand()
     * @generated
     */
    EClass TITLE_COMMAND = eINSTANCE.getTitleCommand();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE_COMMAND__TEXT = eINSTANCE.getTitleCommand_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.CommonCommandImpl <em>Common Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.CommonCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCommonCommand()
     * @generated
     */
    EClass COMMON_COMMAND = eINSTANCE.getCommonCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.DivCommandImpl <em>Div Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.DivCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getDivCommand()
     * @generated
     */
    EClass DIV_COMMAND = eINSTANCE.getDivCommand();

    /**
     * The meta object literal for the '<em><b>Div</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIV_COMMAND__DIV = eINSTANCE.getDivCommand_Div();

    /**
     * The meta object literal for the '<em><b>Div Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIV_COMMAND__DIV_TEXT = eINSTANCE.getDivCommand_DivText();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.CreateImpl <em>Create</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.CreateImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCreate()
     * @generated
     */
    EClass CREATE = eINSTANCE.getCreate();

    /**
     * The meta object literal for the '<em><b>Command</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE__COMMAND = eINSTANCE.getCreate_Command();

    /**
     * The meta object literal for the '<em><b>Bullets</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CREATE__BULLETS = eINSTANCE.getCreate_Bullets();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.TextCommandImpl <em>Text Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.TextCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTextCommand()
     * @generated
     */
    EClass TEXT_COMMAND = eINSTANCE.getTextCommand();

    /**
     * The meta object literal for the '<em><b>Heading</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_COMMAND__HEADING = eINSTANCE.getTextCommand_Heading();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_COMMAND__TEXT = eINSTANCE.getTextCommand_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.DivImpl <em>Div</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.DivImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getDiv()
     * @generated
     */
    EClass DIV = eINSTANCE.getDiv();

    /**
     * The meta object literal for the '<em><b>Division</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIV__DIVISION = eINSTANCE.getDiv_Division();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.TableCommandImpl <em>Table Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.TableCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableCommand()
     * @generated
     */
    EClass TABLE_COMMAND = eINSTANCE.getTableCommand();

    /**
     * The meta object literal for the '<em><b>Rows</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_COMMAND__ROWS = eINSTANCE.getTableCommand_Rows();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.TableRowImpl <em>Table Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.TableRowImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableRow()
     * @generated
     */
    EClass TABLE_ROW = eINSTANCE.getTableRow();

    /**
     * The meta object literal for the '<em><b>Data</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TABLE_ROW__DATA = eINSTANCE.getTableRow_Data();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.TableHeaderImpl <em>Table Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.TableHeaderImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableHeader()
     * @generated
     */
    EClass TABLE_HEADER = eINSTANCE.getTableHeader();

    /**
     * The meta object literal for the '<em><b>Text</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_HEADER__TEXT = eINSTANCE.getTableHeader_Text();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.TableDataImpl <em>Table Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.TableDataImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTableData()
     * @generated
     */
    EClass TABLE_DATA = eINSTANCE.getTableData();

    /**
     * The meta object literal for the '<em><b>Data Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_DATA__DATA_VALUE = eINSTANCE.getTableData_DataValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.InitializerImpl <em>Initializer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.InitializerImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getInitializer()
     * @generated
     */
    EClass INITIALIZER = eINSTANCE.getInitializer();

    /**
     * The meta object literal for the '<em><b>Lang</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INITIALIZER__LANG = eINSTANCE.getInitializer_Lang();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.DropDownCommandImpl <em>Drop Down Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.DropDownCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getDropDownCommand()
     * @generated
     */
    EClass DROP_DOWN_COMMAND = eINSTANCE.getDropDownCommand();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DROP_DOWN_COMMAND__LABEL = eINSTANCE.getDropDownCommand_Label();

    /**
     * The meta object literal for the '<em><b>Options</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DROP_DOWN_COMMAND__OPTIONS = eINSTANCE.getDropDownCommand_Options();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.BulletPointCommandImpl <em>Bullet Point Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.BulletPointCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getBulletPointCommand()
     * @generated
     */
    EClass BULLET_POINT_COMMAND = eINSTANCE.getBulletPointCommand();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference BULLET_POINT_COMMAND__CHILDREN = eINSTANCE.getBulletPointCommand_Children();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.NumberedListCommandImpl <em>Numbered List Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.NumberedListCommandImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getNumberedListCommand()
     * @generated
     */
    EClass NUMBERED_LIST_COMMAND = eINSTANCE.getNumberedListCommand();

    /**
     * The meta object literal for the '<em><b>Children</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NUMBERED_LIST_COMMAND__CHILDREN = eINSTANCE.getNumberedListCommand_Children();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.HtmlCommand <em>Html Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.HtmlCommand
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getHtmlCommand()
     * @generated
     */
    EEnum HTML_COMMAND = eINSTANCE.getHtmlCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.EndHtmlCommand <em>End Html Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.EndHtmlCommand
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getEndHtmlCommand()
     * @generated
     */
    EEnum END_HTML_COMMAND = eINSTANCE.getEndHtmlCommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.CreateBulletPoints <em>Create Bullet Points</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.CreateBulletPoints
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getCreateBulletPoints()
     * @generated
     */
    EEnum CREATE_BULLET_POINTS = eINSTANCE.getCreateBulletPoints();

  }

} //VizPackage
