/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.vizual.viz.CommonCommand;
import org.xtext.example.vizual.viz.VizPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Common Command</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CommonCommandImpl extends CommandImpl implements CommonCommand
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CommonCommandImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VizPackage.Literals.COMMON_COMMAND;
  }

} //CommonCommandImpl
