/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.vizual.viz.Create;
import org.xtext.example.vizual.viz.CreateBulletPoints;
import org.xtext.example.vizual.viz.VizPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Create</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.impl.CreateImpl#getCommand <em>Command</em>}</li>
 *   <li>{@link org.xtext.example.vizual.viz.impl.CreateImpl#getBullets <em>Bullets</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CreateImpl extends CommonCommandImpl implements Create
{
  /**
   * The default value of the '{@link #getCommand() <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommand()
   * @generated
   * @ordered
   */
  protected static final CreateBulletPoints COMMAND_EDEFAULT = CreateBulletPoints.BP;

  /**
   * The cached value of the '{@link #getCommand() <em>Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCommand()
   * @generated
   * @ordered
   */
  protected CreateBulletPoints command = COMMAND_EDEFAULT;

  /**
   * The default value of the '{@link #getBullets() <em>Bullets</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBullets()
   * @generated
   * @ordered
   */
  protected static final String BULLETS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getBullets() <em>Bullets</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getBullets()
   * @generated
   * @ordered
   */
  protected String bullets = BULLETS_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CreateImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return VizPackage.Literals.CREATE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CreateBulletPoints getCommand()
  {
    return command;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCommand(CreateBulletPoints newCommand)
  {
    CreateBulletPoints oldCommand = command;
    command = newCommand == null ? COMMAND_EDEFAULT : newCommand;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VizPackage.CREATE__COMMAND, oldCommand, command));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getBullets()
  {
    return bullets;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setBullets(String newBullets)
  {
    String oldBullets = bullets;
    bullets = newBullets;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, VizPackage.CREATE__BULLETS, oldBullets, bullets));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case VizPackage.CREATE__COMMAND:
        return getCommand();
      case VizPackage.CREATE__BULLETS:
        return getBullets();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case VizPackage.CREATE__COMMAND:
        setCommand((CreateBulletPoints)newValue);
        return;
      case VizPackage.CREATE__BULLETS:
        setBullets((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case VizPackage.CREATE__COMMAND:
        setCommand(COMMAND_EDEFAULT);
        return;
      case VizPackage.CREATE__BULLETS:
        setBullets(BULLETS_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case VizPackage.CREATE__COMMAND:
        return command != COMMAND_EDEFAULT;
      case VizPackage.CREATE__BULLETS:
        return BULLETS_EDEFAULT == null ? bullets != null : !BULLETS_EDEFAULT.equals(bullets);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (command: ");
    result.append(command);
    result.append(", bullets: ");
    result.append(bullets);
    result.append(')');
    return result.toString();
  }

} //CreateImpl
