grammar org.xtext.example.vizual.Viz with org.eclipse.xtext.common.Terminals

generate viz "http://www.xtext.org/example/vizual/Viz"

Model:
	commands+=Command*;

Command:
	Create|Generate
;

Create:
	command = CreateBulletPoints 'with(' bullets=STRING ')'
;

enum CreateBulletPoints:
	BP = 'BP'
;


Generate:
	command = GenerateDefault
;

enum GenerateDefault:
	default='GenerateDefaultDocument'
;
terminal NEW_LINE:
	"\n"
;

terminal TAB_SPACE:
	'\t'
;