/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Main Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.vizual.viz.MainTag#getMainTagName <em>Main Tag Name</em>}</li>
 *   <li>{@link org.xtext.example.vizual.viz.MainTag#getNormalTags <em>Normal Tags</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.vizual.viz.VizPackage#getMainTag()
 * @model
 * @generated
 */
public interface MainTag extends EObject
{
  /**
   * Returns the value of the '<em><b>Main Tag Name</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.vizual.viz.MainTagName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Main Tag Name</em>' attribute.
   * @see org.xtext.example.vizual.viz.MainTagName
   * @see #setMainTagName(MainTagName)
   * @see org.xtext.example.vizual.viz.VizPackage#getMainTag_MainTagName()
   * @model
   * @generated
   */
  MainTagName getMainTagName();

  /**
   * Sets the value of the '{@link org.xtext.example.vizual.viz.MainTag#getMainTagName <em>Main Tag Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Main Tag Name</em>' attribute.
   * @see org.xtext.example.vizual.viz.MainTagName
   * @see #getMainTagName()
   * @generated
   */
  void setMainTagName(MainTagName value);

  /**
   * Returns the value of the '<em><b>Normal Tags</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.vizual.viz.NormalTag}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Normal Tags</em>' containment reference list.
   * @see org.xtext.example.vizual.viz.VizPackage#getMainTag_NormalTags()
   * @model containment="true"
   * @generated
   */
  EList<NormalTag> getNormalTags();

} // MainTag
