/**
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.viz;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normal Tag</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.vizual.viz.VizPackage#getNormalTag()
 * @model
 * @generated
 */
public interface NormalTag extends EObject
{
} // NormalTag
