/**
 * generated by Xtext 2.25.0
 */
package org.xtext.example.vizual.viz;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.vizual.viz.VizFactory
 * @model kind="package"
 * @generated
 */
public interface VizPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "viz";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/vizual/Viz";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "viz";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VizPackage eINSTANCE = org.xtext.example.vizual.viz.impl.VizPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.ModelImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Main Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__MAIN_TAGS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.MainTagImpl <em>Main Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.MainTagImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getMainTag()
   * @generated
   */
  int MAIN_TAG = 1;

  /**
   * The feature id for the '<em><b>Main Tag Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_TAG__MAIN_TAG_NAME = 0;

  /**
   * The feature id for the '<em><b>Normal Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_TAG__NORMAL_TAGS = 1;

  /**
   * The number of structural features of the '<em>Main Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAIN_TAG_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.NormalTagImpl <em>Normal Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.NormalTagImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getNormalTag()
   * @generated
   */
  int NORMAL_TAG = 2;

  /**
   * The number of structural features of the '<em>Normal Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMAL_TAG_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.TextTagImpl <em>Text Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.TextTagImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTextTag()
   * @generated
   */
  int TEXT_TAG = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_TAG__NAME = NORMAL_TAG_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Text Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_TAG_FEATURE_COUNT = NORMAL_TAG_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.impl.ContainerTagImpl <em>Container Tag</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.impl.ContainerTagImpl
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getContainerTag()
   * @generated
   */
  int CONTAINER_TAG = 4;

  /**
   * The feature id for the '<em><b>Normal Tags</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_TAG__NORMAL_TAGS = NORMAL_TAG_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Container Tag</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTAINER_TAG_FEATURE_COUNT = NORMAL_TAG_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.vizual.viz.MainTagName <em>Main Tag Name</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.vizual.viz.MainTagName
   * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getMainTagName()
   * @generated
   */
  int MAIN_TAG_NAME = 5;


  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.example.vizual.viz.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.Model#getMainTags <em>Main Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Main Tags</em>'.
   * @see org.xtext.example.vizual.viz.Model#getMainTags()
   * @see #getModel()
   * @generated
   */
  EReference getModel_MainTags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.MainTag <em>Main Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Main Tag</em>'.
   * @see org.xtext.example.vizual.viz.MainTag
   * @generated
   */
  EClass getMainTag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.MainTag#getMainTagName <em>Main Tag Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Main Tag Name</em>'.
   * @see org.xtext.example.vizual.viz.MainTag#getMainTagName()
   * @see #getMainTag()
   * @generated
   */
  EAttribute getMainTag_MainTagName();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.MainTag#getNormalTags <em>Normal Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Normal Tags</em>'.
   * @see org.xtext.example.vizual.viz.MainTag#getNormalTags()
   * @see #getMainTag()
   * @generated
   */
  EReference getMainTag_NormalTags();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.NormalTag <em>Normal Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normal Tag</em>'.
   * @see org.xtext.example.vizual.viz.NormalTag
   * @generated
   */
  EClass getNormalTag();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.TextTag <em>Text Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Tag</em>'.
   * @see org.xtext.example.vizual.viz.TextTag
   * @generated
   */
  EClass getTextTag();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.vizual.viz.TextTag#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.vizual.viz.TextTag#getName()
   * @see #getTextTag()
   * @generated
   */
  EAttribute getTextTag_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.vizual.viz.ContainerTag <em>Container Tag</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Container Tag</em>'.
   * @see org.xtext.example.vizual.viz.ContainerTag
   * @generated
   */
  EClass getContainerTag();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.vizual.viz.ContainerTag#getNormalTags <em>Normal Tags</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Normal Tags</em>'.
   * @see org.xtext.example.vizual.viz.ContainerTag#getNormalTags()
   * @see #getContainerTag()
   * @generated
   */
  EReference getContainerTag_NormalTags();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.vizual.viz.MainTagName <em>Main Tag Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Main Tag Name</em>'.
   * @see org.xtext.example.vizual.viz.MainTagName
   * @generated
   */
  EEnum getMainTagName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VizFactory getVizFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.ModelImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Main Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__MAIN_TAGS = eINSTANCE.getModel_MainTags();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.MainTagImpl <em>Main Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.MainTagImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getMainTag()
     * @generated
     */
    EClass MAIN_TAG = eINSTANCE.getMainTag();

    /**
     * The meta object literal for the '<em><b>Main Tag Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAIN_TAG__MAIN_TAG_NAME = eINSTANCE.getMainTag_MainTagName();

    /**
     * The meta object literal for the '<em><b>Normal Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAIN_TAG__NORMAL_TAGS = eINSTANCE.getMainTag_NormalTags();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.NormalTagImpl <em>Normal Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.NormalTagImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getNormalTag()
     * @generated
     */
    EClass NORMAL_TAG = eINSTANCE.getNormalTag();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.TextTagImpl <em>Text Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.TextTagImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getTextTag()
     * @generated
     */
    EClass TEXT_TAG = eINSTANCE.getTextTag();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_TAG__NAME = eINSTANCE.getTextTag_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.impl.ContainerTagImpl <em>Container Tag</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.impl.ContainerTagImpl
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getContainerTag()
     * @generated
     */
    EClass CONTAINER_TAG = eINSTANCE.getContainerTag();

    /**
     * The meta object literal for the '<em><b>Normal Tags</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTAINER_TAG__NORMAL_TAGS = eINSTANCE.getContainerTag_NormalTags();

    /**
     * The meta object literal for the '{@link org.xtext.example.vizual.viz.MainTagName <em>Main Tag Name</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.vizual.viz.MainTagName
     * @see org.xtext.example.vizual.viz.impl.VizPackageImpl#getMainTagName()
     * @generated
     */
    EEnum MAIN_TAG_NAME = eINSTANCE.getMainTagName();

  }

} //VizPackage
