/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.vizual.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.vizual.ide.contentassist.antlr.internal.InternalVizParser;
import org.xtext.example.vizual.services.VizGrammarAccess;

public class VizParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(VizGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, VizGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNormalTagAccess().getAlternatives(), "rule__NormalTag__Alternatives");
			builder.put(grammarAccess.getTextTagAccess().getAlternatives_0(), "rule__TextTag__Alternatives_0");
			builder.put(grammarAccess.getMainTagNameAccess().getAlternatives(), "rule__MainTagName__Alternatives");
			builder.put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
			builder.put(grammarAccess.getMainTagAccess().getGroup(), "rule__MainTag__Group__0");
			builder.put(grammarAccess.getTextTagAccess().getGroup(), "rule__TextTag__Group__0");
			builder.put(grammarAccess.getContainerTagAccess().getGroup(), "rule__ContainerTag__Group__0");
			builder.put(grammarAccess.getModelAccess().getMainTagsAssignment_1(), "rule__Model__MainTagsAssignment_1");
			builder.put(grammarAccess.getMainTagAccess().getMainTagNameAssignment_0(), "rule__MainTag__MainTagNameAssignment_0");
			builder.put(grammarAccess.getMainTagAccess().getNormalTagsAssignment_1(), "rule__MainTag__NormalTagsAssignment_1");
			builder.put(grammarAccess.getTextTagAccess().getNameAssignment_1(), "rule__TextTag__NameAssignment_1");
			builder.put(grammarAccess.getContainerTagAccess().getNormalTagsAssignment_2(), "rule__ContainerTag__NormalTagsAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private VizGrammarAccess grammarAccess;

	@Override
	protected InternalVizParser createParser() {
		InternalVizParser result = new InternalVizParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public VizGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VizGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
